// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type OrderStatus string

const (
	OrderStatusPENDINGPAYMENT OrderStatus = "PENDING_PAYMENT"
	OrderStatusPROCESSING     OrderStatus = "PROCESSING"
	OrderStatusSHIPPED        OrderStatus = "SHIPPED"
	OrderStatusCOMPLETED      OrderStatus = "COMPLETED"
	OrderStatusCANCELED       OrderStatus = "CANCELED"
	OrderStatusREFUNDED       OrderStatus = "REFUNDED"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus
	Valid       bool // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type Order struct {
	ID                   uuid.UUID
	UserID               uuid.UUID
	OrderStatus          OrderStatus
	TotalPrice           string
	ShippingAddress      string
	ShippingMethod       string
	ShippingTrackingCode sql.NullString
	PaymentMethod        string
	PaymentGatewayID     sql.NullString
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type OrderItem struct {
	ID          uuid.UUID
	OrderID     uuid.UUID
	ProductID   uuid.UUID
	SellerID    uuid.UUID
	Price       string
	ProductName string
	Quantity    int32
	Description sql.NullString
	CreatedAt   time.Time
}
