// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order_items.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    id,
    order_id,
    product_id,
    seller_id,
    product_name,
    price,
    quantity,
    "description"
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, order_id, product_id, seller_id, price, product_name, quantity, description, created_at
`

type CreateOrderItemParams struct {
	ID          uuid.UUID
	OrderID     uuid.UUID
	ProductID   uuid.UUID
	SellerID    uuid.UUID
	ProductName string
	Price       string
	Quantity    int32
	Description sql.NullString
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, createOrderItem,
		arg.ID,
		arg.OrderID,
		arg.ProductID,
		arg.SellerID,
		arg.ProductName,
		arg.Price,
		arg.Quantity,
		arg.Description,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.SellerID,
		&i.Price,
		&i.ProductName,
		&i.Quantity,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderItemsByOrderID = `-- name: GetOrderItemsByOrderID :many
SELECT id, order_id, product_id, seller_id, product_name,price, quantity, "description" FROM order_items
WHERE order_id = $1
`

type GetOrderItemsByOrderIDRow struct {
	ID          uuid.UUID
	OrderID     uuid.UUID
	ProductID   uuid.UUID
	SellerID    uuid.UUID
	ProductName string
	Price       string
	Quantity    int32
	Description sql.NullString
}

func (q *Queries) GetOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]GetOrderItemsByOrderIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderItemsByOrderIDRow
	for rows.Next() {
		var i GetOrderItemsByOrderIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.SellerID,
			&i.ProductName,
			&i.Price,
			&i.Quantity,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderItemsByOrderIDs = `-- name: GetOrderItemsByOrderIDs :many
SELECT id, order_id, product_id, seller_id, product_name,price, quantity, "description" FROM order_items
WHERE order_id = ANY($1::uuid[])
`

type GetOrderItemsByOrderIDsRow struct {
	ID          uuid.UUID
	OrderID     uuid.UUID
	ProductID   uuid.UUID
	SellerID    uuid.UUID
	ProductName string
	Price       string
	Quantity    int32
	Description sql.NullString
}

func (q *Queries) GetOrderItemsByOrderIDs(ctx context.Context, orderIds []uuid.UUID) ([]GetOrderItemsByOrderIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrderItemsByOrderIDs, pq.Array(orderIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderItemsByOrderIDsRow
	for rows.Next() {
		var i GetOrderItemsByOrderIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.SellerID,
			&i.ProductName,
			&i.Price,
			&i.Quantity,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderWithTrackingCode = `-- name: UpdateOrderWithTrackingCode :one
UPDATE orders
SET shipping_tracking_code = $2, order_status = 'SHIPPED', updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, order_status, total_price, shipping_address, shipping_method, shipping_tracking_code, payment_method, payment_gateway_id, created_at, updated_at
`

type UpdateOrderWithTrackingCodeParams struct {
	ID                   uuid.UUID
	ShippingTrackingCode sql.NullString
}

func (q *Queries) UpdateOrderWithTrackingCode(ctx context.Context, arg UpdateOrderWithTrackingCodeParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, updateOrderWithTrackingCode, arg.ID, arg.ShippingTrackingCode)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderStatus,
		&i.TotalPrice,
		&i.ShippingAddress,
		&i.ShippingMethod,
		&i.ShippingTrackingCode,
		&i.PaymentMethod,
		&i.PaymentGatewayID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
