// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: orders.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const cancelOrder = `-- name: CancelOrder :one
UPDATE orders
SET
    order_status = 'CANCELED',
    updated_at = NOW()
WHERE
    id = $1
    AND user_id = $2
    AND order_status = 'PENDING_PAYMENT' 
RETURNING id, user_id, order_status, total_price, shipping_address, shipping_method, shipping_tracking_code, payment_method, payment_gateway_id, created_at, updated_at
`

type CancelOrderParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) CancelOrder(ctx context.Context, arg CancelOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, cancelOrder, arg.ID, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderStatus,
		&i.TotalPrice,
		&i.ShippingAddress,
		&i.ShippingMethod,
		&i.ShippingTrackingCode,
		&i.PaymentMethod,
		&i.PaymentGatewayID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    id,
    user_id,
    total_price,
    shipping_address,
    shipping_method,
    payment_method
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, user_id, order_status, total_price, shipping_address, shipping_method, shipping_tracking_code, payment_method, payment_gateway_id, created_at, updated_at
`

type CreateOrderParams struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	TotalPrice      string
	ShippingAddress string
	ShippingMethod  string
	PaymentMethod   string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.ID,
		arg.UserID,
		arg.TotalPrice,
		arg.ShippingAddress,
		arg.ShippingMethod,
		arg.PaymentMethod,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderStatus,
		&i.TotalPrice,
		&i.ShippingAddress,
		&i.ShippingMethod,
		&i.ShippingTrackingCode,
		&i.PaymentMethod,
		&i.PaymentGatewayID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItemsForRestock = `-- name: GetItemsForRestock :many
SELECT product_id, quantity FROM order_items
WHERE order_id = $1
`

type GetItemsForRestockRow struct {
	ProductID uuid.UUID
	Quantity  int32
}

func (q *Queries) GetItemsForRestock(ctx context.Context, orderID uuid.UUID) ([]GetItemsForRestockRow, error) {
	rows, err := q.db.QueryContext(ctx, getItemsForRestock, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetItemsForRestockRow
	for rows.Next() {
		var i GetItemsForRestockRow
		if err := rows.Scan(&i.ProductID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT 
    id, 
    user_id, 
    total_price,
    shipping_address, 
    shipping_method, 
    shipping_tracking_code, 
    payment_method, 
    payment_gateway_id, 
    order_status, 
    created_at,
    updated_at
FROM orders 
WHERE id = $1 AND order_status != 'CANCELED' 
LIMIT 1
`

type GetOrderByIDRow struct {
	ID                   uuid.UUID
	UserID               uuid.UUID
	TotalPrice           string
	ShippingAddress      string
	ShippingMethod       string
	ShippingTrackingCode sql.NullString
	PaymentMethod        string
	PaymentGatewayID     sql.NullString
	OrderStatus          OrderStatus
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (GetOrderByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, id)
	var i GetOrderByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalPrice,
		&i.ShippingAddress,
		&i.ShippingMethod,
		&i.ShippingTrackingCode,
		&i.PaymentMethod,
		&i.PaymentGatewayID,
		&i.OrderStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrdersByUserID = `-- name: GetOrdersByUserID :many
SELECT 
    id, 
    user_id, 
    total_price,
    shipping_address, 
    shipping_method, 
    shipping_tracking_code, 
    payment_method, 
    payment_gateway_id, 
    order_status, 
    created_at,
    updated_at
FROM orders
WHERE user_id = $1 AND order_status != 'CANCELED'
ORDER BY created_at DESC
`

type GetOrdersByUserIDRow struct {
	ID                   uuid.UUID
	UserID               uuid.UUID
	TotalPrice           string
	ShippingAddress      string
	ShippingMethod       string
	ShippingTrackingCode sql.NullString
	PaymentMethod        string
	PaymentGatewayID     sql.NullString
	OrderStatus          OrderStatus
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

func (q *Queries) GetOrdersByUserID(ctx context.Context, userID uuid.UUID) ([]GetOrdersByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrdersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrdersByUserIDRow
	for rows.Next() {
		var i GetOrdersByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TotalPrice,
			&i.ShippingAddress,
			&i.ShippingMethod,
			&i.ShippingTrackingCode,
			&i.PaymentMethod,
			&i.PaymentGatewayID,
			&i.OrderStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET order_status = $2, updated_at = NOW()
WHERE id = $1 AND order_status != 'CANCELED'
RETURNING id, user_id, order_status, total_price, shipping_address, shipping_method, shipping_tracking_code, payment_method, payment_gateway_id, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID          uuid.UUID
	OrderStatus OrderStatus
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, updateOrderStatus, arg.ID, arg.OrderStatus)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderStatus,
		&i.TotalPrice,
		&i.ShippingAddress,
		&i.ShippingMethod,
		&i.ShippingTrackingCode,
		&i.PaymentMethod,
		&i.PaymentGatewayID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
